return {
	main = {
		Self = nil,
		Type = "ScreenGui",
		Parent = "PlayerGui",
		Name = "Main",
		IgnoreGuiInset = true,
		ResetOnSpawn = false,
	},
	frame = {
		Self = nil,
		Type = "Frame",
		Parent = "main",
		Name = "Frame",
		AnchorPoint = Vector2.new(0.5,0.5),
		Position = UDim2.new(0.5, 0, 0.5, 0),
		Size = UDim2.new(1, 0, 1, 0),
		BackgroundColor3 = Color3.fromRGB(255,255,255),
		BackgroundTransparency = 1,
		Misc = {
			gradientType = 0,
			cornerType = 0,
			func = nil,
		}
	},
	topBar = {
		Self = nil,
		Type = "TextButton",
		Parent = "frame",
		Name = "TopBar",
		Position = UDim2.new(0.385, 0, 0.272, 0),
		Size = UDim2.new(0.23, 0, 0.026, 0),
		BackgroundColor3 = Color3.fromRGB(95, 99, 118),
		BackgroundTransparency = 0.5,
		BorderSizePixel = 0,
		ZIndex =  2,
		Misc = {
			gradientType = 1,
			cornerType = 0,
			grabbable = true,
			held = false,
		}
	},
	topBarButton = {
		Self = nil,
		Type = "TextButton",
		Parent = "topBar",
		BackgroundColor3 = Color3.fromRGB(53, 54, 67),
		BackgroundTransparency = 0,
		Position = UDim2.new(0.021, 0, 0.203, 0),
		Size = UDim2.new(0.048, 0, 0.557, 0),
		FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json"),
		TextColor3 = Color3.fromRGB(255,255,255),
		TextSize = 14,
		TextScaled = false,
		BorderSizePixel = 0,
		Text = ">",
		ZIndex =  2,
		Misc = {
			gradientType = 1,
			cornerType = 1,
			func = uiCloseOpen,
		}
	},
	topBarText = {
		Self = nil,
		Type = "TextLabel",
		Parent = "topBar",
		AnchorPoint = Vector2.new(0.5,0.5),
		Position = UDim2.new(0.5,0,0.5,0),
		Size = UDim2.new(1,0,1,0),
		TextColor3 = Color3.fromRGB(255,255,255),
		Text = "Dr. Rosploitnik",
		TextSize = 14,
		ZIndex =  2,
		FontFace = Font.new("rbxasset://fonts/families/Inconsolata.json", Enum.FontWeight.Bold),
		BackgroundTransparency = 1,
		Misc = nil
	},
	holder = {
		Self = nil,
		Name = "Holder",
		Type = "Frame",
		Parent = "frame",
		BackgroundColor3 = Color3.fromRGB(44, 47, 50),
		BackgroundTransparency = .5,
		BorderMode = Enum.BorderMode.Outline,
		BorderColor3 = Color3.fromRGB(176, 176, 176),
		BorderSizePixel = 2,
		Position = UDim2.new(0.385, 0, 0.269, 0),
		Size = UDim2.new(0.23, 0, 0.461, 0),
		Misc = {
			gradientType = 1,
		}
	},

	contents = {
		Self = nil,
		Name = "Contents",
		Type = "ScrollingFrame",
		BackgroundTransparency = 1,
		Parent = "holder",
		Position = UDim2.new(0, 0, 0.059, 0),
		Size = UDim2.new(1, 0, 0.941, 0),
		ClipsDescendants = true,
		Misc = {
			uiListLayout = 1,
		}
	},
	-- ESP FRAME --
	espFrame = {
		Self = nil,
		Name = "ESP",
		Type = "Frame",
		Parent = "contents",
		BackgroundColor3 = Color3.fromRGB(20,20,38),
		BackgroundTransparency = 0.5,
		BorderColor3 = Color3.fromRGB(255,255,255),
		BorderMode = Enum.BorderMode.Outline,
		BorderSizePixel = 2,
		LayoutOrder = -1,
		Size = UDim2.new(1,0,0.1,0),
		Misc = {
			gradientType = 1,
		}
	},
	espButton = {
		Self = nil,
		Type = "TextButton",
		BackgroundColor3 = Color3.fromRGB(21,22,30),
		Parent = "espFrame",
		Position = UDim2.new(0.754,0,0.188,0),
		Size = UDim2.new(0.156, 0, 0.61, 0),
		FontFace = Font.new("rbxasset://fonts/families/Inconsolata.json", Enum.FontWeight.Bold),
		Text = "TOGGLE",
		TextColor3 = Color3.fromRGB(255,0,0),
		TextSize = 14,
		Misc = {
			gradientType = 1,
			cornerType = 2,
			func = OnEsp,
		}
	},
	espTextName = {
		Self = nil,
		Type = "TextLabel",
		Parent = "espFrame",
		Position = UDim2.new(0.189,0,0.203,0),
		Size = UDim2.new(0,94,0,20),
		Text = "ESP",
		TextColor3 = Color3.fromRGB(123, 213, 255),
		FontFace = Font.new("rbxasset://fonts/families/Inconsolata.json", Enum.FontWeight.Bold, Enum.FontStyle.Italic),
		TextSize = 22,
		TextScaled = true,
		BackgroundTransparency = 1,
		TextXAlignment = Enum.TextXAlignment.Left,
		AnchorPoint = Vector2.new(0.5 ,0.5),
	},
	espTextDesc = {
		Self = nil,
		Type = "TextLabel",
		Parent = "espFrame",
		Position = UDim2.new(0.189,0,0.678,0),
		Size = UDim2.new(0,94,0,34),
		Text = "See people through walls.",
		TextColor3 = Color3.fromRGB(255,255,255),
		FontFace = Font.new("rbxasset://fonts/families/Inconsolata.json", Enum.FontWeight.Bold, Enum.FontStyle.Italic),
		TextSize = 22,
		TextScaled = true,
		BackgroundTransparency = 1,
		TextXAlignment = Enum.TextXAlignment.Left,
		AnchorPoint = Vector2.new(0.5 ,0.5),
	},
	--
	-- ANTI GRAVITY FRAME --
	antiGravityFrame = {
		Self = nil,
		Name = "antiGravity",
		Type = "Frame",
		Parent = "contents",
		BackgroundColor3 = Color3.fromRGB(20,20,38),
		BackgroundTransparency = 0.5,
		BorderColor3 = Color3.fromRGB(255,255,255),
		BorderMode = Enum.BorderMode.Outline,
		BorderSizePixel = 2,
		LayoutOrder = -1,
		Size = UDim2.new(1,0,0.1,0),
		Misc = {
			gradientType = 1,
		}
	},
	antiGravityButton = {
		Self = nil,
		Type = "TextButton",
		BackgroundColor3 = Color3.fromRGB(21,22,30),
		Parent = "antiGravityFrame",
		Position = UDim2.new(0.754,0,0.188,0),
		Size = UDim2.new(0.156, 0, 0.61, 0),
		FontFace = Font.new("rbxasset://fonts/families/Inconsolata.json", Enum.FontWeight.Bold),
		Text = "TOGGLE",
		TextColor3 = Color3.fromRGB(255,0,0),
		TextSize = 14,
		Misc = {
			gradientType = 1,
			cornerType = 2,
			func = OnFloat,
		}
	},
	antiGravityTextName = {
		Self = nil,
		Type = "TextLabel",
		Parent = "antiGravityFrame",
		Position = UDim2.new(0.189,0,0.203,0),
		Size = UDim2.new(0,94,0,20),
		Text = "Anti Gravity",
		TextColor3 = Color3.fromRGB(123, 213, 255),
		FontFace = Font.new("rbxasset://fonts/families/Inconsolata.json", Enum.FontWeight.Bold, Enum.FontStyle.Italic),
		TextSize = 22,
		TextScaled = true,
		BackgroundTransparency = 1,
		TextXAlignment = Enum.TextXAlignment.Left,
		AnchorPoint = Vector2.new(0.5 ,0.5),
	},
	antiGravityTextDesc = {
		Self = nil,
		Type = "TextLabel",
		Parent = "antiGravityFrame",
		Position = UDim2.new(0.189,0,0.678,0),
		Size = UDim2.new(0,94,0,34),
		Text = "Float.",
		TextColor3 = Color3.fromRGB(255,255,255),
		FontFace = Font.new("rbxasset://fonts/families/Inconsolata.json", Enum.FontWeight.Bold, Enum.FontStyle.Italic),
		TextSize = 22,
		TextScaled = true,
		BackgroundTransparency = 1,
		TextXAlignment = Enum.TextXAlignment.Left,
		AnchorPoint = Vector2.new(0.5 ,0.5),
	},
	--

	speedFrame = {
		Self = nil,
		Name = "Speed",
		Type = "Frame",
		Parent = "contents",
		BackgroundColor3 = Color3.fromRGB(20,20,38),
		BackgroundTransparency = 0.5,
		BorderColor3 = Color3.fromRGB(255,255,255),
		BorderMode = Enum.BorderMode.Outline,
		BorderSizePixel = 2,
		LayoutOrder = -1,
		Size = UDim2.new(1,0,0.1,0),
		Misc = {
			gradientType = 1,
		}
	},
	speedButton = {
		Self = nil,
		Type = "TextButton",
		BackgroundColor3 = Color3.fromRGB(21,22,30),
		Parent = "speedFrame",
		Position = UDim2.new(0.754,0,0.188,0),
		Size = UDim2.new(0.156, 0, 0.61, 0),
		FontFace = Font.new("rbxasset://fonts/families/Inconsolata.json", Enum.FontWeight.Bold),
		Text = "TOGGLE",
		TextColor3 = Color3.fromRGB(255,0,0),
		TextSize = 14,
		Misc = {
			gradientType = 1,
			cornerType = 2,
			func = OnSpeed,
		}
	},
	speedTextName = {
		Self = nil,
		Type = "TextLabel",
		Parent = "speedFrame",
		Position = UDim2.new(0.189,0,0.203,0),
		Size = UDim2.new(0,94,0,20),
		Text = "Super Speed",
		TextColor3 = Color3.fromRGB(123, 213, 255),
		FontFace = Font.new("rbxasset://fonts/families/Inconsolata.json", Enum.FontWeight.Bold, Enum.FontStyle.Italic),
		TextSize = 22,
		TextScaled = true,
		BackgroundTransparency = 1,
		TextXAlignment = Enum.TextXAlignment.Left,
		AnchorPoint = Vector2.new(0.5 ,0.5),
	},
	speedTextDesc = {
		Self = nil,
		Type = "TextLabel",
		Parent = "speedFrame",
		Position = UDim2.new(0.189,0,0.678,0),
		Size = UDim2.new(0,94,0,34),
		Text = "Re-enable to set acceleration and top speed values.",
		TextColor3 = Color3.fromRGB(255,255,255),
		FontFace = Font.new("rbxasset://fonts/families/Inconsolata.json", Enum.FontWeight.Bold, Enum.FontStyle.Italic),
		TextSize = 22,
		TextScaled = true,
		BackgroundTransparency = 1,
		TextXAlignment = Enum.TextXAlignment.Left,
		AnchorPoint = Vector2.new(0.5 ,0.5),
	},
	speedInputVolume = {
		Self = nil,
		Type = "TextBox",
		BackgroundColor3 = Color3.fromRGB(16,16,20),
		BackgroundTransparency = 0,
		ClearTextOnFocus = false,
		Text = "",
		PlaceholderText = "Acceleration",
		Name = "SpeedInputAcceleration",
		Parent = "speedFrame",
		Position = UDim2.new(0.431, 0, 0.333, 0),
		Size = UDim2.new(0, 46, 0, 27),
		TextColor3 = Color3.fromRGB(255,255,255)
	},
	speedInputId = {
		Self = nil,
		Type = "TextBox",
		BackgroundColor3 = Color3.fromRGB(16,16,20),
		BackgroundTransparency = 0,
		ClearTextOnFocus = false,
		Text = "",
		PlaceholderText = "Top Speed",
		Name = "SpeedInputTopSpeed",
		Parent = "speedFrame",
		Position = UDim2.new(0.59, 0, 0.321, 0),
		Size = UDim2.new(0, 46, 0, 27),
		TextColor3 = Color3.fromRGB(255,255,255)
	},
	--
	flyFrame = {
		Self = nil,
		Name = "Fly",
		Type = "Frame",
		Parent = "contents",
		BackgroundColor3 = Color3.fromRGB(20,20,38),
		BackgroundTransparency = 0.5,
		BorderColor3 = Color3.fromRGB(255,255,255),
		BorderMode = Enum.BorderMode.Outline,
		BorderSizePixel = 2,
		LayoutOrder = -1,
		Size = UDim2.new(1,0,0.1,0),
		Misc = {
			gradientType = 1,
		}
	},
	flyButton = {
		Self = nil,
		Type = "TextButton",
		BackgroundColor3 = Color3.fromRGB(21,22,30),
		Parent = "flyFrame",
		Position = UDim2.new(0.754,0,0.188,0),
		Size = UDim2.new(0.156, 0, 0.61, 0),
		FontFace = Font.new("rbxasset://fonts/families/Inconsolata.json", Enum.FontWeight.Bold),
		Text = "TOGGLE",
		TextColor3 = Color3.fromRGB(255,0,0),
		TextSize = 14,
		Misc = {
			gradientType = 1,
			cornerType = 2,
			func = OnFlight,
		}
	},
	flyTextName = {
		Self = nil,
		Type = "TextLabel",
		Parent = "flyFrame",
		Position = UDim2.new(0.189,0,0.203,0),
		Size = UDim2.new(0,94,0,20),
		Text = "Flight",
		TextColor3 = Color3.fromRGB(123, 213, 255),
		FontFace = Font.new("rbxasset://fonts/families/Inconsolata.json", Enum.FontWeight.Bold, Enum.FontStyle.Italic),
		TextSize = 22,
		TextScaled = true,
		BackgroundTransparency = 1,
		TextXAlignment = Enum.TextXAlignment.Left,
		AnchorPoint = Vector2.new(0.5 ,0.5),
	},
	flyTextDesc = {
		Self = nil,
		Type = "TextLabel",
		Parent = "flyFrame",
		Position = UDim2.new(0.189,0,0.678,0),
		Size = UDim2.new(0,94,0,34),
		Text = "(REQUIRES FLOAT ENABLED!!) Fly around.",
		TextColor3 = Color3.fromRGB(255,255,255),
		FontFace = Font.new("rbxasset://fonts/families/Inconsolata.json", Enum.FontWeight.Bold, Enum.FontStyle.Italic),
		TextSize = 22,
		TextScaled = true,
		BackgroundTransparency = 1,
		TextXAlignment = Enum.TextXAlignment.Left,
		AnchorPoint = Vector2.new(0.5 ,0.5),
	},
	--
	
	--
	explodeFrame = {
		Self = nil,
		Name = "Explode",
		Type = "Frame",
		Parent = "contents",
		BackgroundColor3 = Color3.fromRGB(20,20,38),
		BackgroundTransparency = 0.5,
		BorderColor3 = Color3.fromRGB(255,255,255),
		BorderMode = Enum.BorderMode.Outline,
		BorderSizePixel = 2,
		LayoutOrder = -1,
		Size = UDim2.new(1,0,0.1,0),
		Misc = {
			gradientType = 1,
		}
	},
	explodeButton = {
		Self = nil,
		Type = "TextButton",
		BackgroundColor3 = Color3.fromRGB(21,22,30),
		Parent = "explodeFrame",
		Position = UDim2.new(0.754,0,0.188,0),
		Size = UDim2.new(0.156, 0, 0.61, 0),
		FontFace = Font.new("rbxasset://fonts/families/Inconsolata.json", Enum.FontWeight.Bold),
		Text = "TOGGLE",
		TextColor3 = Color3.fromRGB(255,0,0),
		TextSize = 14,
		Misc = {
			gradientType = 1,
			cornerType = 2,
			func = OnExplode,
		}
	},
	explodeTextName = {
		Self = nil,
		Type = "TextLabel",
		Parent = "explodeFrame",
		Position = UDim2.new(0.189,0,0.203,0),
		Size = UDim2.new(0,94,0,20),
		Text = "Explode",
		TextColor3 = Color3.fromRGB(123, 213, 255),
		FontFace = Font.new("rbxasset://fonts/families/Inconsolata.json", Enum.FontWeight.Bold, Enum.FontStyle.Italic),
		TextSize = 22,
		TextScaled = true,
		BackgroundTransparency = 1,
		TextXAlignment = Enum.TextXAlignment.Left,
		AnchorPoint = Vector2.new(0.5 ,0.5),
	},
	explodeTextDesc = {
		Self = nil,
		Type = "TextLabel",
		Parent = "explodeFrame",
		Position = UDim2.new(0.189,0,0.678,0),
		Size = UDim2.new(0,94,0,34),
		Text = "Click to explode things.",
		TextColor3 = Color3.fromRGB(255,255,255),
		FontFace = Font.new("rbxasset://fonts/families/Inconsolata.json", Enum.FontWeight.Bold, Enum.FontStyle.Italic),
		TextSize = 22,
		TextScaled = true,
		BackgroundTransparency = 1,
		TextXAlignment = Enum.TextXAlignment.Left,
		AnchorPoint = Vector2.new(0.5 ,0.5),
	},
	--
	--
	teleportFrame = {
		Self = nil,
		Name = "Teleport",
		Type = "Frame",
		Parent = "contents",
		BackgroundColor3 = Color3.fromRGB(20,20,38),
		BackgroundTransparency = 0.5,
		BorderColor3 = Color3.fromRGB(255,255,255),
		BorderMode = Enum.BorderMode.Outline,
		BorderSizePixel = 2,
		LayoutOrder = -1,
		Size = UDim2.new(1,0,0.1,0),
		Misc = {
			gradientType = 1,
		}
	},
	teleportButton = {
		Self = nil,
		Type = "TextButton",
		BackgroundColor3 = Color3.fromRGB(21,22,30),
		Parent = "teleportFrame",
		Position = UDim2.new(0.754,0,0.188,0),
		Size = UDim2.new(0.156, 0, 0.61, 0),
		FontFace = Font.new("rbxasset://fonts/families/Inconsolata.json", Enum.FontWeight.Bold),
		Text = "TOGGLE",
		TextColor3 = Color3.fromRGB(255,0,0),
		TextSize = 14,
		Misc = {
			gradientType = 1,
			cornerType = 2,
			func = OnTeleport,
		}
	},
	teleportTextName = {
		Self = nil,
		Type = "TextLabel",
		Parent = "teleportFrame",
		Position = UDim2.new(0.189,0,0.203,0),
		Size = UDim2.new(0,94,0,20),
		Text = "Teleport",
		TextColor3 = Color3.fromRGB(123, 213, 255),
		FontFace = Font.new("rbxasset://fonts/families/Inconsolata.json", Enum.FontWeight.Bold, Enum.FontStyle.Italic),
		TextSize = 22,
		TextScaled = true,
		BackgroundTransparency = 1,
		TextXAlignment = Enum.TextXAlignment.Left,
		AnchorPoint = Vector2.new(0.5 ,0.5),
	},
	teleportTextDesc = {
		Self = nil,
		Type = "TextLabel",
		Parent = "teleportFrame",
		Position = UDim2.new(0.189,0,0.678,0),
		Size = UDim2.new(0,94,0,34),
		Text = "Middle click teleport to cursor.",
		TextColor3 = Color3.fromRGB(255,255,255),
		FontFace = Font.new("rbxasset://fonts/families/Inconsolata.json", Enum.FontWeight.Bold, Enum.FontStyle.Italic),
		TextSize = 22,
		TextScaled = true,
		BackgroundTransparency = 1,
		TextXAlignment = Enum.TextXAlignment.Left,
		AnchorPoint = Vector2.new(0.5 ,0.5),
	},
	--
	musicFrame = {
		Self = nil,
		Name = "Music",
		Type = "Frame",
		Parent = "contents",
		BackgroundColor3 = Color3.fromRGB(20,20,38),
		BackgroundTransparency = 0.5,
		BorderColor3 = Color3.fromRGB(255,255,255),
		BorderMode = Enum.BorderMode.Outline,
		BorderSizePixel = 2,
		LayoutOrder = -1,
		Size = UDim2.new(1,0,0.1,0),
		Misc = {
			gradientType = 1,
		}
	},
	musicButton = {
		Self = nil,
		Type = "TextButton",
		BackgroundColor3 = Color3.fromRGB(21,22,30),
		Parent = "musicFrame",
		Position = UDim2.new(0.754,0,0.188,0),
		Size = UDim2.new(0.156, 0, 0.61, 0),
		FontFace = Font.new("rbxasset://fonts/families/Inconsolata.json", Enum.FontWeight.Bold),
		Text = "TOGGLE",
		TextColor3 = Color3.fromRGB(255,0,0),
		TextSize = 14,
		Misc = {
			gradientType = 1,
			cornerType = 2,
			func = OnMusic,
		}
	},
	musicTextName = {
		Self = nil,
		Type = "TextLabel",
		Parent = "musicFrame",
		Position = UDim2.new(0.189,0,0.203,0),
		Size = UDim2.new(0,94,0,20),
		Text = "Music",
		TextColor3 = Color3.fromRGB(123, 213, 255),
		FontFace = Font.new("rbxasset://fonts/families/Inconsolata.json", Enum.FontWeight.Bold, Enum.FontStyle.Italic),
		TextSize = 22,
		TextScaled = true,
		BackgroundTransparency = 1,
		TextXAlignment = Enum.TextXAlignment.Left,
		AnchorPoint = Vector2.new(0.5 ,0.5),
	},
	musicInputVolume = {
		Self = nil,
		Type = "TextBox",
		BackgroundColor3 = Color3.fromRGB(16,16,20),
		BackgroundTransparency = 0,
		ClearTextOnFocus = false,
		Text = "",
		PlaceholderText = "0.5",
		Name = "MusicInputVolume",
		Parent = "musicFrame",
		Position = UDim2.new(0.431, 0, 0.333, 0),
		Size = UDim2.new(0, 46, 0, 27),
		TextColor3 = Color3.fromRGB(255,255,255)
	},
	musicInputId = {
		Self = nil,
		Type = "TextBox",
		BackgroundColor3 = Color3.fromRGB(16,16,20),
		BackgroundTransparency = 0,
		ClearTextOnFocus = false,
		Text = "",
		PlaceholderText = "Asset Id",
		Name = "MusicInputId",
		Parent = "musicFrame",
		Position = UDim2.new(0.59, 0, 0.321, 0),
		Size = UDim2.new(0, 46, 0, 27),
		TextColor3 = Color3.fromRGB(255,255,255)
	},
	musicTextDesc = {
		Self = nil,
		Type = "TextLabel",
		Parent = "musicFrame",
		Position = UDim2.new(0.189,0,0.678,0),
		Size = UDim2.new(0,94,0,34),
		Text = "Add in music id (only number).",
		TextColor3 = Color3.fromRGB(255,255,255),
		FontFace = Font.new("rbxasset://fonts/families/Inconsolata.json", Enum.FontWeight.Bold, Enum.FontStyle.Italic),
		TextSize = 22,
		TextScaled = true,
		BackgroundTransparency = 1,
		TextXAlignment = Enum.TextXAlignment.Left,
		AnchorPoint = Vector2.new(0.5 ,0.5),
	},
	--
	spamFrame = {
		Self = nil,
		Name = "Auto Chat",
		Type = "Frame",
		Parent = "contents",
		BackgroundColor3 = Color3.fromRGB(20,20,38),
		BackgroundTransparency = 0.5,
		BorderColor3 = Color3.fromRGB(255,255,255),
		BorderMode = Enum.BorderMode.Outline,
		BorderSizePixel = 2,
		LayoutOrder = -1,
		Size = UDim2.new(1,0,0.1,0),
		Misc = {
			gradientType = 1,
		}
	},
	spamButton = {
		Self = nil,
		Type = "TextButton",
		BackgroundColor3 = Color3.fromRGB(21,22,30),
		Parent = "spamFrame",
		Position = UDim2.new(0.754,0,0.188,0),
		Size = UDim2.new(0.156, 0, 0.61, 0),
		FontFace = Font.new("rbxasset://fonts/families/Inconsolata.json", Enum.FontWeight.Bold),
		Text = "TOGGLE",
		TextColor3 = Color3.fromRGB(255,0,0),
		TextSize = 14,
		Misc = {
			gradientType = 1,
			cornerType = 2,
			func = OnSpam,
		}
	},
	spamTextName = {
		Self = nil,
		Type = "TextLabel",
		Parent = "spamFrame",
		Position = UDim2.new(0.189,0,0.203,0),
		Size = UDim2.new(0,94,0,20),
		Text = "Auto Chat",
		TextColor3 = Color3.fromRGB(123, 213, 255),
		FontFace = Font.new("rbxasset://fonts/families/Inconsolata.json", Enum.FontWeight.Bold, Enum.FontStyle.Italic),
		TextSize = 22,
		TextScaled = true,
		BackgroundTransparency = 1,
		TextXAlignment = Enum.TextXAlignment.Left,
		AnchorPoint = Vector2.new(0.5 ,0.5),
	},
	spamInputCooldown = {
		Self = nil,
		Type = "TextBox",
		BackgroundColor3 = Color3.fromRGB(16,16,20),
		BackgroundTransparency = 0,
		ClearTextOnFocus = false,
		Text = "",
		PlaceholderText = "Chat Cooldown",
		Name = "SpamInputCooldown",
		Parent = "spamFrame",
		Position = UDim2.new(0.431, 0, 0.333, 0),
		Size = UDim2.new(0, 46, 0, 27),
		TextColor3 = Color3.fromRGB(255,255,255)
	},
	spamInputMessage = {
		Self = nil,
		Type = "TextBox",
		BackgroundColor3 = Color3.fromRGB(16,16,20),
		BackgroundTransparency = 0,
		ClearTextOnFocus = false,
		Text = "",
		PlaceholderText = "Chat Message",
		Name = "SpamInputMessage",
		Parent = "spamFrame",
		Position = UDim2.new(0.59, 0, 0.321, 0),
		Size = UDim2.new(0, 46, 0, 27),
		TextColor3 = Color3.fromRGB(255,255,255)
	},
	spamTextDesc = {
		Self = nil,
		Type = "TextLabel",
		Parent = "spamFrame",
		Position = UDim2.new(0.189,0,0.678,0),
		Size = UDim2.new(0,94,0,34),
		Text = "Spam chat, BEWARE OF PERFORMANCE WITH LOW COOLDOWN.",
		TextColor3 = Color3.fromRGB(255,255,255),
		FontFace = Font.new("rbxasset://fonts/families/Inconsolata.json", Enum.FontWeight.Bold, Enum.FontStyle.Italic),
		TextSize = 22,
		TextScaled = true,
		BackgroundTransparency = 1,
		TextXAlignment = Enum.TextXAlignment.Left,
		AnchorPoint = Vector2.new(0.5 ,0.5),
	},
	--
}
